export default Object.freeze({
  LoadingScreen: "LoadingScreen",
  LoginScreen: "LoginScreen",
  MainDashboardScreen: "MainDashboardScreen",
  StocksScreen: "StocksScreen",
  QuickOrderScreen: "QuickOrderScreen",
  OrderStatusScreen: "OrderStatusScreen",
  PurchaseHistoryScreen: "PurchaseHistoryScreen",
  PaymentsScreen: "PaymentsScreen",
  ViewPercentageScreen: "ViewPercentageScreen",
  PlaceOrderScreen: "PlaceOrderScreen",
  RequestOrOrderScreen: "RequestOrOrderScreen",
  OrderStatusFullScreen: "OrderStatusFullScreen",
  ReceivedScreen:"ReceivedScreen",
  DeliveredScreen:"DeliveredScreen",
  PartiallyDeliveredScreen:"PartiallyDeliveredScreen",
  PaymentGatewayScreen:"PaymentGatewayScreen",
});
